version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            coverage run setup.py test
            coverage report -m
            COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN} coveralls
      - store_artifacts:
          path: test-reports/
          destination: abacus
      - run:
          name: verify git tag vs. package version in setup.py
          command: |
            export CIRCLE_TAG=$(git describe $(git rev-list --tags --max-count=1))
            python setup.py verify

  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: Upload to testpypi or pypi
          command: |
            if [ $CIRCLE_TAG ]; then echo "The package is ready for deployment. Just merge to eiher develop or master branches to do so."; fi
            if [ $CIRCLE_BRANCH = 'master' ]; then sh pypi.sh; fi
            if [ $CIRCLE_BRANCH = 'develop' ]; then sh test_pypi.sh; fi

workflows:
  version: 2
  build-test-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only: /(master|develop)/
