version: 2

jobs:
  build:
    working_directory: ~/abacus_tpot
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: Running tests
          command: |
            echo Running tests
            . venv/bin/activate
            coverage run setup.py test
            coverage report -m
            COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN} coveralls
      - store_artifacts:
          path: test-reports/
          destination: abacus
      - run:
          name: verify git tag vs. package version in setup.py
          command: |
            . venv/bin/activate
            python setup.py verify

  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: Upload to testpypi or pypi
          command: |
            . venv/bin/activate
            if [ $CIRCLE_BRANCH = 'master' ]; then sh pypi.sh; fi
            if [ $CIRCLE_BRANCH = 'develop' ]; then sh test_pypi.sh; fi

workflows:
  version: 2
  build-test-n-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /(master|develop)/
